export const GET_PRODUCTS_DATA = "GET_PRODUCTS_DATA";
export const PRODUCTS_ADD = "PRODUCTS_ADD";

export const GET_CATEGORY_DATA = "GET_CATEGORY_DATA";
export const ADD_CATEGORY_DATA = "ADD_CATEGORY_DATA";